// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBLP3kDk2S_ZYPBuAMshpCdKzUgvDdMAAQ',
    appId: '1:816253000159:web:b58e8178287bc7bc194c6a',
    messagingSenderId: '816253000159',
    projectId: 'class-work-c144b',
    authDomain: 'class-work-c144b.firebaseapp.com',
    storageBucket: 'class-work-c144b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7aLpVcteKjbcwT8MaLQXur8AWLo6qwgQ',
    appId: '1:816253000159:android:accf7a12d68e97c5194c6a',
    messagingSenderId: '816253000159',
    projectId: 'class-work-c144b',
    storageBucket: 'class-work-c144b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLhdL2RUgOop7szuZjw55iiC21Z5rNZiY',
    appId: '1:816253000159:ios:18123ba98fc54e98194c6a',
    messagingSenderId: '816253000159',
    projectId: 'class-work-c144b',
    storageBucket: 'class-work-c144b.appspot.com',
    iosClientId: '816253000159-qrlpj3tdild8e529j7qkoo4sks9o3gk4.apps.googleusercontent.com',
    iosBundleId: 'com.example.moFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLhdL2RUgOop7szuZjw55iiC21Z5rNZiY',
    appId: '1:816253000159:ios:98a68ea30e6d97f1194c6a',
    messagingSenderId: '816253000159',
    projectId: 'class-work-c144b',
    storageBucket: 'class-work-c144b.appspot.com',
    iosClientId: '816253000159-629s3jbkc3o9jcqbn5c0iff9i5ot1e6c.apps.googleusercontent.com',
    iosBundleId: 'com.example.moFinal.RunnerTests',
  );
}
